"""empty message

Revision ID: 22cf94cef660
Revises: af503670ec17
Create Date: 2022-05-01 20:32:38.397678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22cf94cef660'
down_revision = 'af503670ec17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawtime', sa.Column('cycle_time', sa.String(length=64), nullable=True, comment='循环时间'))
    op.drop_column('timetable', 'cycle_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('cycle_time', mysql.VARCHAR(length=64), nullable=True, comment='循环时间'))
    op.drop_column('drawtime', 'cycle_time')
    # ### end Alembic commands ###
