"""empty message

Revision ID: 4772f71416cc
Revises: 22cf94cef660
Create Date: 2022-05-03 10:23:17.595084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4772f71416cc'
down_revision = '22cf94cef660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('is_follow_cycle', sa.Boolean(), nullable=False, comment='是否跟随循环'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'is_follow_cycle')
    # ### end Alembic commands ###
