"""empty message

Revision ID: af503670ec17
Revises: 
Create Date: 2022-05-01 19:45:12.465582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af503670ec17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='权限名称'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_authority_name'), 'authority', ['name'], unique=True)
    op.create_table('drawtime',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('draw_start_time', sa.DateTime(), nullable=False, comment='开始进入抽签时间'),
    sa.Column('draw_end_time', sa.DateTime(), nullable=False, comment='结束进入抽签时间'),
    sa.Column('book_start_time', sa.DateTime(), nullable=False, comment='开始进入抽奖时间'),
    sa.Column('book_end_time', sa.DateTime(), nullable=False, comment='结束进入抽奖时间'),
    sa.Column('place_id', sa.String(length=64), nullable=False, comment='关联场所id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notice',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='内容'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='订单创建时间'),
    sa.Column('place_id', sa.String(length=64), nullable=True, comment='所属场馆id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户id'),
    sa.Column('timetable_id', sa.String(length=64), nullable=True, comment='时间表id'),
    sa.Column('drawtime_id', sa.String(length=64), nullable=True, comment='时间表id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='订单创建时间'),
    sa.Column('book_num', sa.Integer(), nullable=False, comment='订单人数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='订单状态'),
    sa.Column('parent_oder_id', sa.String(length=64), nullable=True, comment='父订单'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('place',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='场所名称'),
    sa.Column('is_open', sa.Boolean(), nullable=False, comment='是否开放'),
    sa.Column('book_frequency', sa.Integer(), nullable=False, comment='可预约次数'),
    sa.Column('img', sa.String(length=128), nullable=True, comment='场所图标路径'),
    sa.Column('parent_id', sa.String(length=64), nullable=False, comment='子场所'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_place_is_open'), 'place', ['is_open'], unique=False)
    op.create_index(op.f('ix_place_name'), 'place', ['name'], unique=True)
    op.create_index(op.f('ix_place_parent_id'), 'place', ['parent_id'], unique=False)
    op.create_table('timetable',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('ticket_num', sa.Integer(), nullable=False, comment='票数'),
    sa.Column('can_book_num', sa.Integer(), nullable=False, comment='可容纳人数'),
    sa.Column('cycle_time', sa.String(length=64), nullable=True, comment='循环时间'),
    sa.Column('initial_ticket_num', sa.Integer(), nullable=False, comment='初始票数'),
    sa.Column('place_id', sa.String(length=64), nullable=False, comment='关联场所id'),
    sa.Column('drawtime_id', sa.String(length=64), nullable=False, comment='关联抽签表id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=64), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('img', sa.String(length=128), nullable=True, comment='用户头像路径'),
    sa.Column('reset_time', sa.DateTime(), nullable=True, comment='重置时间'),
    sa.Column('authority_id', sa.String(length=64), nullable=True, comment='权限id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_place_parent_id'), table_name='place')
    op.drop_index(op.f('ix_place_name'), table_name='place')
    op.drop_index(op.f('ix_place_is_open'), table_name='place')
    op.drop_table('place')
    op.drop_table('order')
    op.drop_table('notice')
    op.drop_table('drawtime')
    op.drop_index(op.f('ix_authority_name'), table_name='authority')
    op.drop_table('authority')
    # ### end Alembic commands ###
